// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Old8Lang.PackageManager.Server.Data;

#nullable disable

namespace Old8Lang.PackageManager.Server.Migrations
{
    [DbContext(typeof(PackageManagerDbContext))]
    partial class PackageManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Old8Lang.PackageManager.Server.Models.ApiKeyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ApiKeys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 20, 14, 24, 20, 222, DateTimeKind.Utc).AddTicks(9500),
                            Description = "开发环境使用的默认 API 密钥",
                            ExpiresAt = new DateTime(2026, 12, 20, 14, 24, 20, 222, DateTimeKind.Utc).AddTicks(9500),
                            IsActive = true,
                            Key = "I8p-vzOkGX6WVkCKh65GH9EXf0A9pgXHxv3s0D5TpVs=",
                            Name = "Development API Key",
                            Scopes = "package:read,package:write,admin:all",
                            UsageCount = 0
                        });
                });

            modelBuilder.Entity("Old8Lang.PackageManager.Server.Models.PackageDependencyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DependencyId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PackageEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetFramework")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionRange")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageEntityId");

                    b.ToTable("PackageDependencies");
                });

            modelBuilder.Entity("Old8Lang.PackageManager.Server.Models.PackageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsListed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrerelease")
                        .HasColumnType("INTEGER");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DownloadCount");

                    b.HasIndex("PackageId");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("PackageId", "Version")
                        .IsUnique();

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Old8Lang.PackageManager.Server.Models.PackageFileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PackageEntityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PackageEntityId");

                    b.ToTable("PackageFiles");
                });

            modelBuilder.Entity("Old8Lang.PackageManager.Server.Models.PackageTagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PackageEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageEntityId");

                    b.ToTable("PackageTags");
                });

            modelBuilder.Entity("Old8Lang.PackageManager.Server.Models.PackageDependencyEntity", b =>
                {
                    b.HasOne("Old8Lang.PackageManager.Server.Models.PackageEntity", "Package")
                        .WithMany("PackageDependencies")
                        .HasForeignKey("PackageEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Old8Lang.PackageManager.Server.Models.PackageFileEntity", b =>
                {
                    b.HasOne("Old8Lang.PackageManager.Server.Models.PackageEntity", "Package")
                        .WithMany("Files")
                        .HasForeignKey("PackageEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Old8Lang.PackageManager.Server.Models.PackageTagEntity", b =>
                {
                    b.HasOne("Old8Lang.PackageManager.Server.Models.PackageEntity", "Package")
                        .WithMany("PackageTags")
                        .HasForeignKey("PackageEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Old8Lang.PackageManager.Server.Models.PackageEntity", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("PackageDependencies");

                    b.Navigation("PackageTags");
                });
#pragma warning restore 612, 618
        }
    }
}
